# DB設定（ローカル用の例）
# db.url=jdbc:mysql://localhost:3306/project_kanri?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
# db.user=project
# db.password=project

db.url=jdbc:mysql://localhost:3306/project_kanri?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo

db.user=project

db.password=project
